# Generated by Django 4.1.3 on 2022-11-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('inn', models.TextField(blank=True, null=True)),
                ('position', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
