# Generated by Django 4.1.3 on 2022-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nii', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('start_date', models.CharField(max_length=50, verbose_name='Дата начала')),
                ('end_date', models.CharField(max_length=50, verbose_name='Дата окончания')),
                ('amount_of_financing', models.CharField(max_length=20, verbose_name='Объем финансирования')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['-data'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='employees',
            name='data',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='inn',
            field=models.TextField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='middle_name',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
    ]
