# Generated by Django 4.1.3 on 2022-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nii', '0002_projects_alter_employees_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='data',
            field=models.CharField(max_length=30, verbose_name='Дата рождения'),
        ),
    ]
