# Generated by Django 4.1.3 on 2022-12-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nii', '0004_employees_num_ser'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='employeess',
            field=models.ManyToManyField(to='nii.employees'),
        ),
    ]
