# Generated by Django 4.1.3 on 2022-12-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nii', '0005_projects_employeess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['-num_ser'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='employeess',
            field=models.ManyToManyField(to='nii.employees', verbose_name='Сотрудники'),
        ),
    ]
