# Generated by Django 4.1.3 on 2022-12-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nii', '0006_alter_employees_options_alter_projects_employeess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='num_ser',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Номер и серия паспорта'),
        ),
    ]
